### ISSUE TITLE
Bug: Autodetect freezes the program

### ISSUE THREAD

**Issue by thiswastheonlyavailableusername** [arteme/pod-ui#33]
I don't know what the button is supposed to do, but as soon as I press it, the program freezes and I have to close it.

Windows 11, Pod 2.0, latest pod-ui version

**Comment by arteme** [comment]
Hi! Awesome username there!

The "autodetect" button is supposed to open all possible MIDI ports and send device inquiry messages out to figure out, where the POD answers from. You can manually select the MIDI in/out ports, select that  and press "test" to test if the POD is communicating correctly.

I haven't tried the app on Windows 11, only on Windows 10, but it works correctly here. You can also try the "winrt" build if you haven't tried it already.

**Comment by thiswastheonlyavailableusername** [comment]
Wow, super responsive!
Yup, winrt version works. What's the difference?

**Comment by arteme** [comment]
Great news!

The "winrt" build uses a set of newer APIs (UWP, https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/midi) which are a part  of a newer WinRT runtime available in since Windows 8 and everyone in Windows 10+ should probably be using this.

The other build uses the legacy Windows Multimedia API (WinMM) which has been in Windows since the beginning.

I'll try if I can get my setup to work with Windows 11 and maybe I'll be able to reproduce this problem there. What sound card do you use to plug the MIDI cables into?
